nginx:
  container_name: nginx
  build: ./nginx
  ports:
    - "8080:80"
  volumes:
    # source
    - ./src/:/usr/share/nginx/html
  links:
    - php_fpm
php_fpm:
  container_name: php_fpm
  build: ./php-fpm
  volumes:
    - ./src/:/usr/share/nginx/html
  links:
    - mysql

mysql:
  image: mysql:5.7
  container_name: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=123456